# Generated by Django 5.2 on 2025-04-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_alter_mentorados_navigators_disponibilidadehorarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
